development:
  clients:
    default:
      database: bropoints
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: bropoints_test
      hosts:
        - localhost:27017
